nordnet/nordnet-ui-kit

package.json
You need webpack as a dependency to actually build the project. Unless you have it installed globally, which you shouldn't.
=> webpack dependency needed to build

src/components/input/input-default.jsx
We need the event to be passed to onBlur, also adding it to onFocus for future-proofing in case it will be needed as well.
=> Added event to input onFocus and onBlur

src/components/ratio-bar/ratio-bar.jsx, src/components/ratio-bar/ratio-bar.scss, src/components/select/select.jsx, test/components/ratio-bar/ratio-bar.test.js
* Fixes issues where the bars got "unfortunate" widths (∑`widths` > 100%) and therefore overflowed to the next line.
* Adds `labelUp` and `labelDown` so that we can send in translations there.
=> Ratio bar fixes

package.json
To avoid errors like these with newer React versions:
```
Warning: Unknown prop `minWidth` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
in input (created by AutosizeInput)
in div (created by AutosizeInput)
in AutosizeInput (created by Select)
in div (created by Select)
in div (created by Select)
in Select (created by Select)
in Select (created by AccountSelector)
in div
in Col (created by AccountSelector)
in AccountSelector (created by Connect(AccountSelector))
in Connect(AccountSelector) (created by App)
in div
in Row (created by App)
in div
in Grid (created by App)
in div (created by App)
in App (created by Connect(App))
in Connect(App) (created by IntlProviderApp)
in IntlProvider (created by IntlProviderApp)
in IntlProviderApp …
```
=> Bump react-select to avoid prop warnings

src/components/graph/themes/base.js
This setting lets you decide how much you can zoom. The highcharts default way of calculating a good min range is working fine and therefore this value shouldn't be set.
=> removed minrange config for xaxis

src/components/graph/graph.jsx, src/components/graph/graph.md, src/components/graph/themes/base.js, src/components/graph/themes/index.js, src/components/graph/themes/muted.js, src/components/range-selector/range-selector.jsx, src/components/range-selector/range-selector.scss
This adds a new theme to Graph and RangeSelector that looks like this:
Isn't that neat? :)
=> Add a muted variant for Graph theme and RangeSelector

src/components/button/button.scss
There was feedback from the team that when you hovered a button the cursor did not change to a pointing hand as expected. Added this feature.
=> hovering a button shows pointing finger cursor instead of arrow

package.json
- Bumped react-svg-sprite-icon to fix problems with icons in IE11
- Fixed react peerDeps to be 15.x
- Forced babel-polyfill to 6.16.0 to fix IE problems in dev-mode
=> bump react-svg-sprite-icon and fix peerDeps

src/components/alert/alert-styles.jsx, src/components/alert/alert.jsx
From design:
New implementation:
Gray background to see where component ends now when shadow is removed.
=> Alert updated design

src/components/segmented-control/index.js, src/components/segmented-control/segmented-control-styles.jsx, src/components/segmented-control/segmented-control.jsx, src/components/segmented-control/segmented-control.md
The different options are sent in as child nodes. The `value` prop of these children is used. See the markdown file.
=> Created a SegmentedControl component

src/components/icon/icon.md
To make it easier to find a specific icon the layout was changed:
From this: 
To this:
=> Re-work how icons get presented in the documentatation

src/components/flag/flags/cn.jsx, src/components/flag/flags/eu.jsx, src/components/flag/flags/gb.jsx, src/components/flag/flags/jp.jsx
Prepending the ids used in the flags with the name of the flag.
Fixes #207.
=> Avoid id collision with the flags

src/components/button/button-styles.jsx, src/components/button/button.jsx, src/components/button/button.md
This fixes #212.
Also in the same PR I added better handling of the disabled states, which we previously did not have in the corresponding modifier colors.
From the design:
New implementation:
=> Make default buttons gray. New modifier="action" to make them blue.

src/components/input/input-default-styles.jsx
Issue was visible in firefox on narrow input fields:
=> Fix addonRight for small input fields

src/components/button/button-styles.jsx, src/components/button/button.jsx
Add a span with position relative to workaround IE specific focus "animation"
=> fix(Button): Remove button text animation in IE

src/components/animate/animate.jsx, src/components/animate/modifierHeight.js, test/components/animate/animate.test.js
Two things solved in this PR:
* Require prop "animationName" when creating an Animate. 
* Add wrapping div around children of Animate to solve the problem when the children has top or bottom padding
Side effect: Now we should only have single child in each Animate.
=> Animate enhancement

src/components/table/table-styles.jsx, src/components/tbody/tbody-styles.jsx, src/components/td/td-styles.jsx, src/components/th/th-styles.jsx, src/components/thead/thead-styles.jsx, src/components/tr/tr-styles.jsx
* Change breakpoint from sm to md
* Change overflow to scroll instead of auto on iOS
* Add -webkit-overflow-scrolling: touch to make scrolling smoother on
iOS
=> fix(Table): 💄 Make horizontal scrolling work on iOS devices

src/components/animate/animate.jsx, src/components/animate/animate.md, src/components/animate/modifierHeight.js
* This makes it possible to have more than one child and still make it animate.
* Also added the required `animationName` to the markdown example file.
This fixes #237
=> Change Animate wrapper component to be a div

src/components/animate/modifierHeight.js
Use height as well as max-height. This makes the animation stutter less in Firefox. Less work calculating reflows during animation.
=> fix(Animate): SHEL-167 Animate component. Use height as well as max-height

README.md
`[text][/link]` does not appear to be valid syntax. I changed it to `[text](/link)` instead
=> docs(README): Fix docs links for 1.7.0

src/components/alert/alert.jsx, test/components/alert/alert.test.js
add dismissedCallback prop so that consumers can know when the component has been dismissed
=> feat(Alert Component): add dismissedCallback prop

src/components/pane/pane.jsx, test/components/pane/pane.test.js
component is now listening to prop change of activeTab prop, making it possible but not required to
handle the component tab state from outside.
=> feat(<Pane />): make it possible to change active tab from outside

src/components/progress-bar/progress-bar-styles.jsx, src/components/progress-bar/progress-bar.jsx, src/components/progress-bar/progress-bar.md, test/components/progress-bar/progress-bar.test.js
Setting the **highlightActive** property will highlight the active (current) value, so that the user can clearly see which step they are currently at.
=> feat(ProgressBar): add 'highlightActive' option

src/components/input/input-checkbox-radio.jsx
Changed proptype for label in input-checkobox-radio from string to node
=> feat(front-end): Changed proptype for radio label

src/components/input/input-default-styles.jsx, src/components/input/input-default.jsx
This should've been in the previous PR, but it was merged before I managed to push. Theoretically this is a breaking change, since we change from `px` to `em`. But I know for a fact that nobody uses this component yet, so IMO we can label this as a refactor and skip the release.
=> refactor(input[textarea]): Move style into CSS file

src/components/input/input-default-styles.jsx
Set padding to 0 and define a height in order to make inputs have the same
height across browsers. Here are before-and-after screenshots from Chrome, Firefox and Internet Explorer:
The red lines are absolute-positioned behind the inputs to illustrate the difference between before (left column) and after (right column).
=> fix(Input): Reset input padding and set height

src/components/animate/animate.jsx
only set overflow: hidden during animation so that components such as tooltips inside animated
component dont get cropped
=> fix(<Animate/>): overflow hidden duing animation instead of always

src/components/alert/alert-styles.jsx, src/styles/color.js, src/styles/palette.js
Addresses the main part of #336. I've left `yellowLight` as I'm unable to determine if it's used and removing it may be considered a breaking change.
=> fix(Style): update yellow color

src/components/spinner/spinner.jsx, test/components/spinner/spinner.test.js
This avoids:
```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div
    in Spinner (created by Jss(Spinner))
```
when using us a spinner inside of certain elements. The spinner is already set to `inline-block` so this should have no downstream effects.
=> fix(Spinner): wrapper as a span to avoid console errors

documentation/template.html, src/components/tooltip/tooltip.jsx
Solves the case when a tooltip should fit (although barely) but gets rendered off screen. This happens since:
1. The default space from the edge (10) is to big
2. The meta viewport tag is invalid, which makes `window.innerWidth` to behave badly.
Fixes #339
=> fix(Tooltip): Prevent tooltip from going off screen on mobile

.gitignore, src/components/tooltip/tooltip-styles.jsx, src/components/tooltip/tooltip.jsx
With the change that was made to icons they are now set to inherit from their color from their parent. This syncs that same behavior.
I'm following up with design for if words/svgs should have any color when they have a tooltip and will handle that separately if it changes.
=> fix(tooltip): color should inherit from parent as all icons do

src/components/table-cell/table-cell-styles.jsx, src/components/table/data.js, src/components/table/table.md
Added an example and padding left/right. Without left/right padding the cells can touch eachother if there is too much content. There doesn't seem to be any issue with the left/right padding on the other examples.
=> fix(table): Add limited width example and never allow the table cells to touch

src/components/logo/logo.jsx
the black nordnet text is always visisble in ie 11
=> fix(logo): hide nordnet text when onlyIcon is set

src/components/flag/flag.jsx
Use position absolute on round flags to position the svg correctly in the circle.
Previous: 
With the fix:
=> fix: Fix render issue for small flags

src/components/thead/thead-styles.jsx, src/components/thead/thead.jsx, src/components/tr/tr-styles.jsx, src/components/tr/tr.jsx
Doesn't break the api, nor any functionality. I simply wrap the `Tr` and `Thead` components in a component that injects dynamic stylesheets only when needed (when `stickyOffset` is used, which it hardly is, but that's different problem). 
Tested in modern browsers and works as before. It works just as before in IE as well, the problem is that `sticky` is not [supported](https://caniuse.com/#feat=css-sticky) in IE so it has never worked there.
Perhaps the most important of all the stylesheet fixes. Will dramatically improve performance as we use tables so frequently.
=> fix too many dynamic stylesheets for table

src/components/editable-input/editable-input-styles.jsx, src/components/editable-input/editable-input.jsx
Buttons where getting squished together on IE/Edge and the cursor was not moving to the end of the input on focus.
I also adjusted the size of the Edit button to be the same height as the Submit/Cancel buttons.
=> fix(editable-input): adjust size of edit button and fix ie/edge bugs

src/components/popup-menu/popup-menu.jsx
Our current implementation depends on the button being focused on click, so we need to manually make sure that it's focused through the browser api...
Also added some minor documentation that should have been included in my last PR.
=> Make sure that button is focused on click

src/components/thead/thead-styles.jsx
add z-index to table head cells to solve sticky table head problem when scrolling
=> fix: add z-index to table head cells

src/components/button/button-styles.jsx, src/components/button/button.jsx
Icons currently are only supported to the left of text. This adds support to add an icon above text. Matches the behavior of the modal:
Example:
=> feat(button): support icon above the text

src/components/input/input-select.jsx, src/components/input/input.md
Add support for opgroups in <Input type="select"/> by letting option objects have options themselves.
=> feat(Input): add optgroup support for input type=select

src/components/flag/flag.jsx, test/components/flag/flag.test.js
Fixed some QA comments:
* positioning is off in the search and in the market performance widget
* not enough space to display the borders of the flag on page watchlist and on page account details
=> fix(Flag): fix so that flag inherits styles passed as props

src/components/editable-input/editable-input-styles.jsx, src/components/editable-input/editable-input.jsx
=> fix(EditableInput): Wrap submit/cancel-buttons on mobile

src/components/show-more/show-more-styles.js
Safari has a quirk when rendering transparent in linear-gradients causing the gradient to darken instead. Using rgba resolves that issue.
Before: 
After:
Verified that it looks good in: 
Safari 12
Chrome 70
Firefox 63
IE 11
Edge 42
=> fix: resolve styling bug in safari

src/components/subsection/subsection-styles.js, src/components/subsection/subsection.jsx
for some reason safari v <= 10 cannot apply flex properties when container is a button
=> fix(Subsection): fix subsection for safari 10

package.json, src/components/table-cell/table-cell.jsx, yarn.lock
In IE and Edge the header border on the tables does not render correctly if the `<th>` is empty. 
Expected:
Actual:
This is caused by a parent component having `display: flex` that Edge picks up and incorrectly applies it to the` div` in the `th`. I have not been able to override this effect. 
The fix in this PR injects a white space in any table cell that would otherwise be empty. Hence, render the table correctly.
=> Empty table headers

src/components/table-content-wrapper/shapes.js, src/components/table-content-wrapper/table-body/table-body-row/table-body-row.jsx
Allow adding 
tdProps: {
unstyledChild: true,
ellipsis: false,
},
to cols definition
=> fix(TableContentWrapper): add possibility to extend Td props

src/components/popup-menu/popup-menu-list.jsx, src/components/popup-menu/popup-menu.jsx, src/components/popup-menu/popup-menu.md
Allow passing className down to dropdown menu.
This allows specifying z-index in consumer.
=> fix(PopupMenu): add prop popupMenuDropdownClassName

src/components/table-cell/table-cell.jsx, src/components/thead/thead-styles.jsx
Fixing issue in edge where the bottom border on Th elements went all over the place.
=> fix: add height 100% to th and th:after to fix border issue in edge

src/components/table-content-wrapper/table-body/table-body-row/table-body-row.styles.js
<button> adds unnecessary big padding, overriding this
=> fix(TableContentWrapper): fix sidescrolling issue

.travis.yml
Use Node 10 for publish, and use latest yarn version. Travis defaults to yarn v1.3.2, which besides being slower results in this deprecation warning https://travis-ci.org/nordnet/nordnet-ui-kit/jobs/486925473#L462
=> ci: use newer versions in travis

.travis.yml
CI on all branches, and linting in CI. Closes #528
So before, we only ran CI on PRs because we got "double builds" for PRs otherwise. See here for why that's actually desirable https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests, as me, @iamstarkov and @Dhq found out.
=> ci(travis): bring back ci on all branches

.travis.yml
Build docs and babel in ci. @iamstarkov and I talked about this, needed for renovate to ensure that nothing crashes from a PR.
=> ci: build in CI

package.json, src/components/deprecate/deprecate.js, src/components/deprecate/deprecate.test.js, src/components/deprecate/index.js, src/components/flag/flag.jsx, src/components/instrument-badge/instrument-badge.jsx, src/components/pane/pane.jsx, src/components/segmented-control/segmented-control.jsx, src/components/tabs/tabs.jsx, yarn.lock
To ensure that developers see that the components they use are deprecated. Otherwise we're never gonna be able to remove some of these components, as we were made aware when releasing v3.
=> fix: add deprecation warning HOCs

.travis.yml
@iamstarkov and I talked, and since we don't ship any code that uses node, we don't actually need to run tests with node 8.
Also only runs build in the test stage for PRs, not on publish. That would be unnecessary because the publish step then proceeds to run build again for the publishing.
=> ci: only use node 10 and dont test build on publish

package.json
I got some husky warnings on my machine, turns out that they have changed how it's supposed to be configured https://github.com/typicode/husky#upgrading-from-014 But thankfully they had a `./node_modules/.bin/husky-upgrade` so this is just a run of that and now committing and pushing works without warnings.
=> chore: fix deprecated husky configs and cleanup package.json

.travis.yml, package.json, renovate.json
* Reduces the number of stages in travis, to avoid having to wait for environments to spin up twice for test and build, which can be done in the same environment.
* Disables coveralls, which has started to fail us. The problem is, as discussed on their side. Let's find a suitable alternative when we have time. I'm open for in some way *trying* to run coveralls, but not failing with non-zero exit code if coveralls fails (on their side), thus having to retrigger the whole build.
* groups all non-major renovate bumps in the same PR, to avoid being spammed with PRs for dev dependencies.
=> chore: travis and renovate fixes

.travis.yml, package.json, yarn.lock
validate-commit-msg is [deprecated](https://www.npmjs.com/package/validate-commit-msg) so I replaced it with commitlint as recommended, and also enabled commitlint in CI 🎉
=> chore: replace validate-commit-msg with commitlint

src/components/editable-input/editable-input-styles.jsx
The desired result is to get the following behaviour on our pages:
At 'lg' and wider, use the full width:
Between 'md' and 'lg', have the buttons on the next row, aligned to the right:
And on smaller view widths, most importantly mobile, have the input and buttons on two rows, buttons centered:
=> fix(editable-input): adjust positioning of buttons per mixin breakpoint

src/styles/typography.js
`sans` should be `sans-serif`, and I replaced Open Sans with a [native font stack](https://getbootstrap.com/docs/4.0/content/reboot/#native-font-stack) as fallback.
=> fix: font stack

package.json, yarn.lock
Add [plugin](https://github.com/watson/commitlint-config-squash-pr) for allowing longer squashed messages (since a squash adds the PR number) and disable the annoying scope case rule so that for instance `feat(Button)` is allowed (same as our internal config).
=> chore: fix commitlint config

src/components/button/button-styles.jsx
make text bigger, not increasing height on buttons, width is slightly increased on size xs.
=> fix(button): adjust font size and paddings

src/components/rating/rating.jsx, src/components/rating/rating.md, src/components/rating/rating.test.js
The Rating component used to default to max rating when rating data was missing. I suggest this instead.
=> fix(Rating): use a sensible default instead of max rating

src/styles/breakpoints.js, src/styles/typography.js
Before we had mobile typography styles for all devices if their viewports is less than 360px, which is almost no devices. Instead mobile styles will now be for everything under 768px viewport.
=> fix: make mobile actually get mobile styles

src/styles/typography.js
Because we changed the mobile breakpoint of typography the media query was overriding the developers media query and vice versa depending on order
=> fix: make style not override developers code

src/components/table/table-styles.jsx
table breaking due to bug with dynamic style in media query bug in jss 10
=> fix(Table): fix table breaking due to dynamic style
