nordnet/nordnet-ui-kit

- package.json
Please also bump the version of nordnet-ui-kit after this :)
> Update react-svg-sprite-icon to 0.0.10

- src/components/widget/widget.jsx
- src/components/widget/widget.md
- src/components/widget/widget.scss
This PR will add padding to the top of the widget when no header is supplied.
> Add padding to widget when no header is present

- src/components/icon/icon.jsx
- src/components/logo/logo.jsx
- test/components/alert/alert.test.js
- test/components/badge/badge.test.js
- test/components/button/button.test.js
- test/components/date-picker/date-picker.test.js
- test/components/icon/icon.test.js
- test/components/input/input.test.js
- test/components/labeled-value/labeled-value.test.js
- test/components/logo/logo.test.js
- test/components/pane/pane.test.js
- test/components/select/select.test.js
- test/components/widget/widget.test.js
- Added tests for components without tests
- Extended tests for some components with only basic tests
- Fixed warnings on Button component tests
- Added an default prop type to Logo component
> Added tests

- src/components/input/input-select.jsx
* Fixes unknown props warning in input type select where options is sent as a prop
* Fixes #64
> Fix unknown prop warning

- documentation/rsg-components/Layout/Layout.scss
- documentation/rsg-components/Layout/Renderer.jsx
- package.json
- src/components/date-picker/date-picker.md
* Fix Renderer and Layout to allow isolated components
* Update initialState in date picker
> Bump react-styleguidist

- webpack.config.babel.js
Added react-dom to externals in webpack config.
> react-dom as external dependency

- package.json
- webpack.config.babel.js
Since we need to be able to include nordnet-ui-kit as global library on the page, we need to have a UMD version.
> Added support to build UMD version of nordnet-ui-kit

- src/index.js
- webpack.config.babel.js
Forgot to export the new flag component...
> Export Flag

- src/components/range-selector/range-selector.jsx
#83 Removed count as it is unused. Made it possible to provide selected range in props.
> Selected range as props

- src/components/graph/themes/dark.js
- src/components/graph/themes/light.js
The colors of the text that will be printed onto the graph when no data is available.
> added no-data label colors to themes

- src/components/select/select.scss
Signed-off-by: Ross Malpass <Ross.Malpass@nordnet.se>
> Updated the style of the Select component.

- src/components/alert/alert.scss
> change default color on alertbox

- CHANGELOG.md
- src/components/alert/alert.jsx
- src/components/dropdown/dropdown.jsx
- src/components/input/help-text.jsx
- src/components/input/input-checkbox-radio.jsx
- src/components/input/input-default.jsx
- src/components/input/input-select.jsx
- src/index.js
- styleguide.config.js
This is the quickfix for exposing the components Input, Dropdown, Alert, NavBar.
> Quickfix for Input, Dropdown, Alert, NavBar

- src/components/dropdown/dropdown-styles.jsx
- src/components/dropdown/dropdown.jsx
- src/styles/palette.js
Old implementation:
New implementation:
Design file:
> Updated design for Dropdown component

- src/components/labeled-value/labeled-value.jsx
Slight improvement to the LabeledValue.
Medium and large sizes adjusted according to design.
> Updated font size for LabeledValue

- src/components/badge/badge.jsx
From design:
New implementation:
> Badge design

- src/components/input/input-checkbox-radio-styles.jsx
- src/components/input/input-default-styles.jsx
- src/components/input/input-default.jsx
> Input design

- src/components/badge/badge.jsx
> Badge style update

- src/components/table/style-utilities.jsx
- src/components/table/table.jsx
- src/components/table/table.md
- src/components/td/td-styles.jsx
- src/components/tfoot/tfoot-styles.jsx
- src/components/th/th-styles.jsx
- src/components/thead/thead-styles.jsx
> Some improved Table styling

- src/components/input/input-default-styles.jsx
See commit messages for detailed description of changes. 
Before:
After:
> Input fixes

- src/components/segmented-control/segmented-control-styles.jsx
- src/components/segmented-control/segmented-control.jsx
- src/components/segmented-control/segmented-control.md
New API where you specify `type` (`radio` or `checkbox`).
With the `checkbox` type, you can add `checked` prop to set start value. See markdown example.
> Added option on segmented control to work as a toggle button

- src/components/alert/alert-styles.jsx
- src/components/alert/alert.jsx
- src/components/alert/alert.md
> Vertical option for Alert component

- src/components/dropdown/dropdown.jsx
> Dropdown component close when clicking outside

- src/components/input/input-select-styles.jsx
- src/components/input/input-select.jsx
- test/components/input/input.test.js
> Styling updates for Input component

- src/components/button/button-styles.jsx
- src/components/button/button.jsx
- src/components/button/button.md
According to input from Theresa and MIG-2596 Jira issue.
> Updated secondary buttons

- package.json
- src/components/animate/animate.jsx
- src/components/animate/animate.md
- src/components/animate/index.js
- src/components/animate/modifierHeight.js
- src/index.js
- src/styles/transitions/durations.js
- src/styles/transitions/easings.js
- src/styles/transitions/index.js
- src/styles/transitions/transitionModifiers/index.js
- src/styles/transitions/transitionModifiers/modifierHeight.js
- test/components/animate/animate.test.js
- yarn.lock
New features:
* A new component called Animate. This is what will be used primarily.
* A transition modifier for animating height. This is what Animate uses internally.
This zip contains a recording of how the animation looks.
[animate_component.zip](https://github.com/nordnet/nordnet-ui-kit/files/1025360/animate_component.zip)
Screenshot from the new documentation:
> SHEL-165 Animate component and transition modifiers

- .travis.yml
* more test environments
* dont run CI on version bumps
* releases are happening only in master and are skipped in pull-requests
> build(travis): better CI and releases

- CHANGELOG.md
- src/components/alert/alert-styles.jsx
Alert modifier thickness style change from 2px to 4px
None
> style($browser): Alert modifier thickness style change

- src/index.js
Just a simple forgotten import/export
> fix(SegmentedControl): Export added

- src/components/td/td-styles.jsx
Decrease padding from 13px to 10px.
> style(Td): Decrease padding.

- src/components/button/button-styles.jsx
Increase padding and decrease font size for all button sizes
> fix(Button): update style according to design

- src/components/icon/icons/addMoney.jsx
- src/components/icon/icons/index.js
> feat(Icon): Add 'AddMoney' icon

- src/components/radio-group/radio-group.jsx
Radiogroup now listens to componentWillReceiveProps
> feat: Added support for componentWillReceiveProps in readiogroup

- src/components/input/input-default-styles.jsx
- src/components/input/input.md
Changes proposed:
* If there is no label the input will not get any bottom margin compensating for that label.
Another approach would be to have another prop like `noMarginBottom` and remove the margin then. What do you guys think?
> fix(Input): Remove marginBottom if no label is given

- src/components/segmented-control/segmented-control-styles.jsx
Remove a margin-right that seem to not have any practical function
> fix(SegmentedControl): remove a margin-right

- src/components/instrument-badge/instrument-badge.jsx
- src/components/instrument-badge/instrument-badge.md
Fixed a bug where InstrumentBadge wouldn't display correctly in IE
> fix(InstrumentBadge): ie fix

- src/components/icon/icons/hexagon.jsx
- src/components/instrument-badge/instrument-badge.jsx
- src/components/instrument-badge/instrument-badge.md
Adde subTextFontSize to ommit on InstrumentBadge
> fix(InstrumentBadge): ommit prop

- src/components/progress-bar/index.js
- src/components/progress-bar/progress-bar-styles.jsx
- src/components/progress-bar/progress-bar.jsx
- src/components/progress-bar/progress-bar.md
- src/index.js
- src/styles/mixins.js
- test/components/progress-bar/progress-bar.test.js
> feat(ProgressBar): added ProgressBar component.

- src/components/icon/icons/profile.jsx
Adjust profile icon horizontal position
> fix(Icon): Adjust profile icon

- src/components/button/button-styles.jsx
This is one step towards making the buttons behave consistently on all browsers. 
Animations should be the next step.
> feat(Button): add Active state support

- package.json
- yarn.lock
> fix(jss-theme-reactor): bump jss-theme-reactor to get rid off prop-types warnings

- src/components/shareville-logo/index.jsx
- src/components/shareville-logo/shareville-logo.md
- src/index.js
- test/components/shareville-logo/logo.test.js
Add 2 version of the Shareville logo: with and without logotype
> feat: Add Shareville logo

- src/components/button/button-styles.jsx
- src/components/button/button.md
Prevent it from modifying normal icons in the button:
> fix(Buttons): only size svgs provided via the `icon` prop

- src/components/table/data.js
- src/components/table/style-utilities.jsx
- src/components/table/table-styles.jsx
- src/components/table/table.jsx
- src/components/table/table.md
- src/components/tbody/tbody-styles.jsx
- src/components/td/td-styles.jsx
- src/components/td/td.jsx
- src/components/th/th-styles.jsx
- src/components/th/th.jsx
- src/components/thead/thead-styles.jsx
- src/components/thead/thead.jsx
- src/components/tr/tr-styles.jsx
- test/components/table/td/td.test.js
New props: flexBasisMobile, flexBasisScreen, alignMobile, alignScreen, tableDataTitle, tableDataOrder
> feat(Table): Add mobile list for tables

- package.json
- prettier.config.js
- src/styles/palette.js
- yarn.lock
This change will make the config look like it does in our internal projects.
> Add prettier config

- src/components/subsection/index.js
- src/components/subsection/subsection-styles.js
- src/components/subsection/subsection.jsx
- src/components/subsection/subsection.md
- src/index.js
- test/components/subsection/subsection.test.js
> feat: Add subsection component

- package.json
- src/components/popup-menu/index.js
- src/components/popup-menu/popup-menu-item.jsx
- src/components/popup-menu/popup-menu.jsx
- src/components/popup-menu/popup-menu.md
- src/components/popup-menu/popup-menu.styles.js
- src/index.js
- yarn.lock
adds popup menu previously used only in page-watchlist
> feat(popup-menu): adds popup menu

- src/components/button/button.jsx
- src/components/button/button.md
button will render as button element rather than anchor when supplied with both href and disabled
> fix(button): fix disable for button with href

- package.json
- yarn.lock
https://nodesecurity.io/advisories/577
> fix: Upgrade vulnerable version of lodash

- src/components/subsection/subsection-styles.js
- src/components/subsection/subsection.jsx
- src/components/subsection/subsection.md
- test/components/subsection/subsection.test.js
> fix(SubSection): Fix SubSection SSR

- src/components/segmented-control/segmented-control.jsx
when clicking an item in SegmentetControl handleChange was triggered twice
> fix(segmentet-control): multiple onchange when clicking

- src/components/input/input-checkbox-radio-styles.jsx
Adjusts checkbox and radio button borders to be a little darker
> fix(Input): Checkbox and radio border color

- src/components/button/button-styles.jsx
- src/components/button/button.jsx
- src/components/button/button.md
Follow up to #420 
Had some local spacing that I missed and I've also added examples as punishment for my crime.
> fix(button): button spacing and add examples

- src/components/tr/tr-styles.jsx
don't know why they were there but it created issues with different length on borderBottom
> fix(Table): remove transparent borders

- src/components/popup-menu/popup-menu.jsx
> fix: add type button to popup menu button

- src/components/pane/pane.md
- src/components/popup-menu/popup-menu-item.jsx
this prevents form to submit on click by default
> fix: add type to button

- src/components/alert/alert-styles.jsx
Leave margin to not interfere with close button:
Prev: 
In PR:
> fix(Alert): padding to not block close button

- src/components/popup-menu/popup-menu-list.jsx
- src/components/popup-menu/popup-menu.jsx
- src/components/popup-menu/popup-menu.md
Reverts nordnet/nordnet-ui-kit#495
> Revert "fix(PopupMenu): add prop popupMenuDropdownClassName"

- src/components/popup-menu/popup-menu-list.jsx
- src/components/popup-menu/popup-menu.jsx
- src/components/popup-menu/popup-menu.md
Allow specifying z-index on the dropdown from the popupMenu
> fix(PopupMenu): add prop popupMenuDropdownZIndex

- now.json
- package.json
- src/components/deprecate/deprecate.js
So that we can see the changes without checking out the branch locally. 🎉
> Preview deploy all PRs to now

- .travis.yml
- package.json
I messed up the conditional for one to run the test build on travis.
> ci(travis): fix test build conditional

- src/components/editable-input/editable-input.jsx
- src/components/editable-input/editable-input.md
- src/components/editable-input/editable-input.test.js
adds sensitive prop which will display the value as four asterisks if it is active
> feat(editableinput): adds sensitive prop to EditableInput

- package.json
- src/components/animate/animate.md
- src/components/avatar/avatar.md
- src/components/button/button.md
- src/components/flag/flag.md
- src/components/icon/icon.md
- src/components/pagination/pagination.md
- src/components/popup-menu/popup-menu.md
- src/components/radio-group/radio-group.md
- src/components/rating/rating.md
- src/components/segmented-control/segmented-control.md
- src/components/subsection/subsection.md
- src/components/table/table.md
- src/components/tabs/tabs.md
- src/components/tooltip/tooltip.md
- src/components/ul/ul.md
- styleguide.config.js
- yarn.lock
As you can see, the examples got a _lot_ clearer 🎉
> chore: styleguidist 9

- src/components/input/help-text.jsx
- src/components/input/input-default-styles.jsx
- src/components/input/input.md
solves problem of help text bleeding into input and label
> fix(input): adjust positioning and margins of help text

- src/components/rating/rating.styles.js
- src/components/tabs/tab/tab-styles.jsx
- src/components/tabs/tabs-styles.jsx
@nordnet/ui plx review and merge and release
> fix: ratings color and tabs font size

- src/components/badge/badge.jsx
- src/components/button/button-styles.jsx
- src/components/input/input-default-styles.jsx
- src/components/input/input-select-styles.jsx
- src/components/pagination/page/page-styles.jsx
- src/components/progress-bar/progress-bar-styles.jsx
- src/components/segmented-control/segmented-control-styles.jsx
- src/components/tooltip/tooltip-styles.jsx
adjusted some button paddings to make it look better
> feat: remove border-radius

- src/components/flag/flag.jsx
- src/components/input/checkbox.jsx
- src/components/input/checkbox.test.js
- src/components/table/tr/tr-styles.jsx
Problems after introduction of a11yColors
> fix: imports of color

- src/styles/color.js
So I accidentally mixed up the a11y and normal colors with each other 😅Also I added more a11y alternatives for the brand colors.
> More a11y color fixes

- src/styles/typography.js
Updated font sizes according to design
> fix: update font sizes
